### ISSUE TITLE
Missing --quiet argument as in mkfs.ext*

### ISSUE THREAD

**Issue by swedebugia** [dosfstools/dosfstools#103]
According to e2fsprogs man page:
       -q     Quiet execution.  Useful if mke2fs is run in a script.

**Comment by pali** [comment]
Why this option is useful for mkfs.fat? If script does not want output then it can throw it away via redirection to /dev/null. And 1:1 compatibility with mke2fs does not make sense as ext4 is totally different filesystem as FAT and has totally different options. Also other formatting tools for other filesystems uses different command line options.
