### ISSUE TITLE
Nintendo DSi does not recognise sd card when formating even with zeroing the device before

### ISSUE THREAD

**Issue by nicman23** [dosfstools/dosfstools#108]
On windows guest with block device pass and a slow format, with the same sector options, everything works.

**Comment by pali** [comment]
Can you provide SD card dump after formatted by Windows and by mkfs.fat? Please specify also which version of mkfs.fat are you using and also parameters used for formatting.

**Comment by nicman23** [comment]
i no longer have a windows install, when i do i ll reopen this

**Comment by pali** [comment]
You can also format your SD card in `Nintendo DSi` which should work fine. And compare it with formatting by `mkfs.fat`. Dump from `Nintendo DSi` internal formatting tool can be also useful to detect how it differs from `mkfs.fat`.
