### ISSUE TITLE
No support for huge file systems.

### ISSUE THREAD

**Issue by stoeckmann** [dosfstools/dosfstools#118]
fsck.fat does not support huge filesystems. To protect memory layout, hard checks have been implemented at these places:

- https://github.com/dosfstools/dosfstools/blob/master/src/boot.c#L484
- https://github.com/dosfstools/dosfstools/blob/master/src/boot.c#L497
- https://github.com/dosfstools/dosfstools/blob/master/src/boot.c#L504
- https://github.com/dosfstools/dosfstools/blob/master/src/boot.c#L508

Especially on 32 bit architectures without large file support this can be already triggered with partitions larger than 2 GB.

**Comment by pali** [comment]
I'm closing this issue as dosfstools support huge filesystems.

in autoconf is already `AC_SYS_LARGEFILE` macro which enables compilation with large file support (LFS):
https://github.com/dosfstools/dosfstools/blob/cc7514352cee68a8cdcb9ab50f37dc1e1e4b893a/configure.ac#L50

LFS is required for huge filesystems on 32bit architectures and it is already provided/supported. Note that LFS is the only way how to use huge filesystems on 32bit architectures on Linux.

**Comment by stoeckmann** [comment]
I have to disagree here.

As stated in autoconf documentation:
> Large-file support can be disabled by configuring with the --disable-largefile option.

The thing is that a partition, even on a system without large file support (be it forced by configuration for easier reproduction or limitations), can be larger than 2 GB. Therefore the fsck check would fail on valid partitions on such systems. The OFF_MAX value, which depends on the system itself, should not be used for file system limits which have fixed values.

**Comment by pali** [comment]
If you disable LFS support at compile time, you obviously cannot access large filesystems.

So if you run non-LFS fsck binary on partition which is larger then 2GB it will fail and there is no way to do anything with it. You have to recompile fsck binary without disabling lfs.

**Comment by pali** [comment]
OFF_MAX value is value with last sector of disc which system can access. So if fsck is compiled without LFS then there is no way to access sectors after 2GB space.

**Comment by stoeckmann** [comment]
I see. Granted, this situation is rare anyway. So "filesystem is too large" is more like a statement that it's too large for this system, not in general being corrupt. Okay!

**Comment by pali** [comment]
Yes, it means it is "too large for running fsck binary". If you think that message is misleading or some other improvements could be done, let me kwno. But really if you compile fsck without LFS, you cannot access large files.

Here is simple program for demonstration:
```c
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
int main() {
    int fd = open("big", O_RDONLY);
    if (fd < 0) {
        perror("open");
        return 1;
    }
    if (lseek(fd, 0, SEEK_END) == (off_t)-1) {
        perror("lseek");
        return 1;
    }
    return 0;
}
```
If you compile it on 32bit system without LFS and run, you would get:
```
$ truncate -s 10G big
$ i686-linux-gnu-gcc test.c
$ ./a.out 
lseek: Value too large for defined data type
```
If you compile it on 32bit system with LFS then it correctly can access end of file:
```
$ truncate -s 10G big
$ i686-linux-gnu-gcc test.c -D_FILE_OFFSET_BITS=64
$ ./a.out
```
(no error)
