### ISSUE TITLE
Can't build statically linked version for arm

### ISSUE THREAD

**Issue by brownls** [dosfstools/dosfstools#127]
I've tried giving -static in CFLAGS and cannot find any mention of what this build needs to produce the binary without being linked to a shared library.  I didn't see anything in configure's help output such as --enable-static.  I don't know if this is the right place to put this but don't see any other forums to get assistance.  TIA

**Comment by pali** [comment]
Try: `./configure LDFLAGS="--static"`. `CFLAGS` is for compiling and `LDFLAGS` for linking.
