### ISSUE TITLE
Dynamically Linked ARM and PPC Travis builds are failing

### ISSUE THREAD

**Issue by davidgumberg** [dosfstools/dosfstools#130]
https://travis-ci.org/davidgumberg/dosfstools

I was losing hair trying to figure out why #129 was failing build, don't know much about build stuff, but travis segfaults when running the tests on my master branch (even with this one) with the dynamic link ARM and PPC builds, even though it says this branch is passing build so something must have changed with the versions of the dynamic libraries since the build was last done 3 months ago I'm guessing.

**Comment by pali** [comment]
IIRC Travis updated their machines from Ubuntu Trusty to Ubuntu Xenial and this is probably reason for failing tests.

But your changes with removal of needed gconv libraries probably do not fix it. I think you just found bug in tests scripts that they accept failing tests...
