### ISSUE TITLE
mkfs.fat fails to format 2G NVMe partition

### ISSUE THREAD

**Issue by mcepl** [dosfstools/dosfstools#139]
(Originally filed on openSUSE bugzilla as https://bugzilla.suse.com/1172863)

Trying to run mkfs.vfat to create the EFI partition on an NVMe-over-Fabrics device results in:
```sh
# mkfs.fat /dev/nvme0n1p1
mkfs.fat 4.1 (2017-01-24)
WARNING: Not enough clusters for a 32 bit FAT!
mkfs.fat: Attempting to create a too large filesystem
# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    0 931.5G  0 disk 
├─sda1        8:1    0   500M  0 part /boot/efi
├─sda2        8:2    0    40G  0 part 
├─sda3        8:3    0    40G  0 part /
├─sda4        8:4    0  31.2G  0 part [SWAP]
├─sda5        8:5    0    40G  0 part 
└─sda6        8:6    0  31.2G  0 part 
nvme0n1     259:1    0    32G  0 disk 
├─nvme0n1p1 259:2    0   1.9G  0 part 
├─nvme0n1p2 259:3    0   1.9G  0 part 
└─nvme0n1p3 259:4    0  28.3G  0 part /mnt
```
and the installation will report an error.

Curiously enough, 'mkfs.vfat -F 32 -S 2 /dev/nvme0n1p1' works:
```
# mkfs.vfat -F 32 -s 2 /dev/nvme0n1p1
mkfs.fat 4.1 (2017-01-24)
# blkid /dev/nvme0n1p1
/dev/nvme0n1p1: UUID="077B-E051" TYPE="vfat" PARTLABEL="boot" PARTUUID="7f8c144a-15b5-49ae-93f7-b5665c4c178a"
```
Why do I have to specify these parameters?

**Comment by pali** [comment]
Could you try to use version from git?

I know that cluster parameter calculation in mkfs.fat is incorrect and I have fixes for it, but they depends on my already open pull requests. Therefore I can create a pull request with calculation fixes after my all open pull requests are reviewed and merged.

**Comment by pali** [comment]
Note that external bug link is not accessible.

**Comment by mcepl** [comment]
> Note that external bug link is not accessible.

Give me your email address on openSUSE Bugzilla and I will add you to the CC list.

**Comment by pali** [comment]
It would be better to have all details available publically, so other people who watch this github issue could read all information and could either provide patch/fix/comment. I'm probably not the only person here.

But I can understand that external bug link/report is not open to everybody and in some situation cannot be (e.g. it may contain sensitive information, etc.).

**Comment by mcepl** [comment]
> It would be better to have all details available publically, so other people who watch this github issue could read all information and could either provide patch/fix/comment. I'm probably not the only person here.
> 
> But I can understand that external bug link/report is not open to everybody and in some situation cannot be (e.g. it may contain sensitive information, etc.).

There is not anything really secret about the bug, but the bug has been reported against the enterprise SLE distribution, and these bugs are kept secret as matter of policy. Getting you on CC, it would be easier to communicate with the original bug reporter, but I can pass the messages in between you if you prefer that.

**Comment by pali** [comment]
Well, currently I do not have time to look deeply at this issue. I can look at it later, after all my other patches for dosfstools project are reviewed and merged. Just I do not want to prepare and open another set (conflicting to my existing) changes to dosfstools.

This is why I said that probably other people could be interested in details about this issue more then me.

**Comment by mcepl** [comment]
Refiled as https://bugzilla.suse.com/1172909 which is publicly accessible.

**Comment by tomty89** [comment]
Isn't this a dup of #111?

**Comment by pali** [comment]
Can you check if pull request https://github.com/dosfstools/dosfstools/pull/153 fixes this issue?

**Comment by pali** [comment]
#153 was merged

**Comment by dm17** [comment]
I have a similar scenario with 1GB, nvme, but no error at end - just the warning. No warning if I use 'mkfs.vfat -F 32 -S 2 /dev/nvme0n1p1'... Either way there seemed to be no issue until I mounted it and see the 'df -h' reports 491K instead of 1024MB. I'm not sure how to debug this - any ideas?
