### ISSUE TITLE
Minor issue in man pages

### ISSUE THREAD

**Issue by hmartink** [dosfstools/dosfstools#145]
Dear dosfstools maintainer,
the manpage-l10n project maintains a large number of translations of
man pages both from a large variety of sources (including dosfstools) as
well for a large variety of target languages.

During their work translators notice different possible issues in the
original (english) man pages. Sometimes this is a straightforward
typo, sometimes a hard to read sentence, sometimes this is a
convention not held up and sometimes we simply do not understand the
original.

We use several distributions as sources and update regularly (at
least every 2 month). This means we are fairly recent (some
distributions like archlinux also update frequently) but might miss
the latest upstream version once in a while, so the error might be
already fixed. We apologize and ask you to close the issue immediately
if this should be the case, but given the huge volume of projects and
the very limited number of volunteers we are not able to double check
each and every issue.

Secondly we translators see the manpages in the neutral po format,
i.e. converted and harmonized, but not the original source (be it man,
groff, xml or other). So we cannot provide a true patch (where
possible), but only an approximation which you need to convert into
your source format.

Finally the issues I'm reporting have accumulated over time and are
not always discovered by me, so sometimes my description of the
problem my be a bit limited - do not hesitate to ask so we can clarify
them.

I'm now reporting the errors for your project. If future reports
should use another channel, please let me know.

Man page: fatlabel.8
Issue: set → sets

"B<fatlabel> set or gets a MS-DOS filesystem label from a given device."

**Comment by pali** [comment]
Hello! Could you please create a pull request with changes? Also in future the preferred way for any fixes, including documentation is to create a pull request. So everything would be at one place and would not be lost. Thanks!

**Comment by hmartink** [comment]
Hello Pali,
as explained in my text this is unfortunately not possible.
Greetings
             Helge

**Comment by pali** [comment]
Well, reporting issue with description of changes which cannot be applied automatically by machine, instead of opening a pull request or proving a patch just take lot of more developer time. And for projects like this one, where the main maintainer does not have a free time to read "instructions from issue" how to create a patch and then apply it, just complicate inclusion of reported change...

**Comment by hmartink** [comment]
As stated, manpages-l10n handles now 10 languages (and growing) and > 100 upstream projects and effectively just one person reporting the issues this is unfortunately not possible. And the changes are listed at the end of the text and in your case is very trivial (a spelling).  Also if this is easier for you  (would be for me), I could send the changes by e-mail as well. 

And a second one was discovered recently:
Man page: fatlabel.8
Issue: fatlabel → B<fatlabel>

"MS-DOS and Windows systems use DOS (OEM) codepage for encoding and decoding "
"FAT label. In Windows systems DOS codepage is global for all running "
"applications and cannot be configured explicitly. It is set implicitly by "
"option I<Language for non-Unicode programs> available in I<Regional and "
"Language Options> via I<Control Panel>. Default DOS codepage for fatlabel is "
"850. See following mapping table between DOS codepage and Language for non-"
"Unicode programs:"

**Comment by pali** [comment]
As stated, this project does not have enough power to handle every change which cannot be applied automatically by tooling.

So please provide valid pull request on github or patch in standard unified diff format which is widely used and can be applied directly to the project. Everythig else just increase maintenance cost and take time which we do not have.

**Comment by hmartink** [comment]
Then we cannot come together. I took a huge effort to inform each and every upstream (> 100) the best I can, if you cannot go the last mile then that is sad, but that's it. It's way beyond my time budget to check out > 100 repositories, find out where exactly the source is, provide a patch, go through various interfaces and so on.

**Comment by pali** [comment]
In last weeks I did a huge effort to finally release a new version 4.2 after 2 years. If I should go that your way, and trying to find what to change and so, like you suggest, this project would be already dead as I would just doing this "find code" stuff.

Contribution is simple: Please open a pull request with your change, CI integration will automatically run tests that pull request with your changes is OK and then I can review and merge it.

All other contributors are doing it in this way and this is standard way in the most github project.

I could accept alternative way without need to register on github, by providing a patch in unified diff format which can be cleanly applied on top of the master git branch.

But I do not have a time for any other fancy options. If your tool cannot provide patch in unified diff format which is de-facto standard across all projects, then sorry, your tool is broken and I'm even not going to investigate this broken tool. You should change it.

Sorry, but I do not have time for this discussion.
