### ISSUE TITLE
mkfs.fat: sector count integer overflow in -v output for big block counts

### ISSUE THREAD

**Issue by dkl** [dosfstools/dosfstools#151]
With mkfs.fat 4.1 from Ubuntu, and also from latest git, there seems to be an overflow of the sector count in the -v output, if the block count value specified on the command line is high enough:

> **$ rm -f foo && mkfs.fat -v -F 32 -C foo $((1024 * 1024 * 1024 * 1))**
> mkfs.fat 4.1 (2017-01-24)
> foo has 255 heads and 63 sectors per track,
> hidden sectors 0x0000;
> logical sector size is 512,
> using 0xf8 media descriptor, **with -2147483648 sectors**;
> drive number 0x80;
> filesystem has 2 32-bit FATs and 64 sectors per cluster.
> FAT size is 262144 sectors, and provides 33546239 clusters.
> There are 64 reserved sectors.
> Volume ID is bb7790ea, no volume label.
> **$ rm -f foo && mkfs.fat -v -F 32 -C foo $((1024 * 1024 * 1024 * 2))**
> mkfs.fat 4.1 (2017-01-24)
> Warning: target too large, space at end will be left unused
> foo has 255 heads and 63 sectors per track,
> hidden sectors 0x0000;
> logical sector size is 512,
> using 0xf8 media descriptor, **with -1 sectors**;
> drive number 0x80;
> filesystem has 2 32-bit FATs and 64 sectors per cluster.
> FAT size is 524224 sectors, and provides 67092480 clusters.
> There are 64 reserved sectors.
> Volume ID is bf64d55b, no volume label.

The created sparse image file has the correct size though (1 TiB and 2 TiB respectively for these commands), so I think it's just a problem in the -v output. I tested only on 64bit system (x86_64-linux) so far.

**Comment by pali** [comment]
Can you check if pull request https://github.com/dosfstools/dosfstools/pull/153 fixes this issue?

**Comment by dkl** [comment]
Yes, that fixes it.

**Comment by pali** [comment]
#153 was merged
