### ISSUE TITLE
Does mkfs.fat overwrite data?

### ISSUE THREAD

**Issue by mb720** [dosfstools/dosfstools#157]
Hi and thanks a lot for dosfstools!

[Since Windows Vista](https://docs.microsoft.com/en-US/troubleshoot/windows-server/backup-and-storage/format-command-not-write-zeros-to-disk), formatting on Windows overwrites all data on the volume with zeros when doing a full format (as opposed to a quick format).

What's the behavior of `mkfs.fat` in this regard? Does it overwrite data outside the file allocation table?

**Comment by pali** [comment]
> Does it overwrite data outside the file allocation table?

No.
