### ISSUE TITLE
Release 4.2 will not allow underscore in VFAT labels

### ISSUE THREAD

**Issue by mdhorn** [dosfstools/dosfstools#160]
Attempting to make a vfat file system with a label "XXX_YYY" is failing with release 4.2 with the error message:
`Labels with characters *?.,;:/\\|+=<>[]\" are not allowed`

Underscore is not in the invalid list in this error message, not in the documentation I can find regarding restrictions on VFAT labels.

It appears that commit 77c3de9bac572 introduced this problem and is now forbidding the use of the underscore character in VFAT labels.

We have a use case for years that requires an underscore in the label name.

**Comment by pali** [comment]
Can you provide more information? How you are trying to create filesystem, on which system, etc..

Because I have no problem to create a filesystem with `XXX_YYY` label on Debian 10. Here is my output:
```
$ ./src/mkfs.fat -C -n XXX_YYY -v /tmp/fat 10240
mkfs.fat 4.2 (2021-01-31)
/tmp/fat has 2 heads and 32 sectors per track,
hidden sectors 0x0000;
logical sector size is 512,
using 0xf8 media descriptor, with 20480 sectors;
drive number 0x80;
filesystem has 2 16-bit FATs and 4 sectors per cluster.
FAT size is 20 sectors, and provides 5101 clusters.
There are 4 reserved sectors.
Root directory contains 512 slots and uses 32 sectors.
Volume ID is 9483a42b, volume label XXX_YYY.
```
```
$ ./src/fatlabel /tmp/fat
XXX_YYY
```

**Comment by mdhorn** [comment]
In attempting to create a reproducible test case for you, found that we've been embedding double-quotes in a vfat label for a long time. 🤦 

Closing as not a bug. Sorry for the noise. Thanks for the fix. 👍
