### ISSUE TITLE
unexpected changes 

### ISSUE THREAD

**Issue by patatetom** [dosfstools/dosfstools#162]
hi,
can i continue to use the `%` character in the label or will it end up as a prohibited character ?
why did you introduce a ban rather than a warning ?
regards.

**Comment by pali** [comment]
> can i continue to use the `%` character in the label or will it end up as a prohibited character ?
> why did you introduce a ban rather than a warning ?

Can you describe your issue with `%` character little bit a more? Because I do not see that it is prohibited and it is working fine for me:

```
$ ./src/mkfs.fat -v -C -n % /tmp/fat 1000
mkfs.fat 4.2+git (2021-01-31)
/tmp/fat has 2 heads and 16 sectors per track,
hidden sectors 0x0000;
logical sector size is 512,
using 0xf8 media descriptor, with 2000 sectors;
drive number 0x80;
filesystem has 2 12-bit FATs and 4 sectors per cluster.
FAT size is 2 sectors, and provides 490 clusters.
There is 1 reserved sector.
Root directory contains 512 slots and uses 32 sectors.
Volume ID is 943862aa, volume label %.
$ ./src/fatlabel /tmp/fat 
%
$ ./src/fatlabel /tmp/fat '%A%'
$ ./src/fatlabel /tmp/fat 
%A%
$ ./src/fsck.fat -v /tmp/fat 
fsck.fat 4.2+git (2021-01-31)
Checking we can access the last sector of the filesystem
Boot sector contents:
System ID "mkfs.fat"
Media byte 0xf8 (hard disk)
       512 bytes per logical sector
      2048 bytes per cluster
         1 reserved sector
First FAT starts at byte 512 (sector 1)
         2 FATs, 12 bit entries
      1024 bytes per FAT (= 2 sectors)
Root directory starts at byte 2560 (sector 5)
       512 root directory entries
Data area starts at byte 18944 (sector 37)
       490 data clusters (1003520 bytes)
16 sectors/track, 2 heads
         0 hidden sectors
      2000 sectors total
Checking for unused clusters.
/tmp/fat: 1 files, 0/490 clusters
```

**Comment by patatetom** [comment]
until version 4.1(-3), I used the character `:` in my label and it worked perfectly, whether with Linux or Windows.
the arrival of version 4.2(-1), with an update of my system, forced me to use another _singular_ character (other than a number or a letter) and I wanted to know if the new character I had just chosen would last for a long time.

I would have preferred a big warning (as for lowercase letters) rather than an error output.

**Comment by pali** [comment]
In version 4.2 was completely rewritten/redisigned support for labels as it was incompatible with windows systems, FAT specification, SD card specifications and also incompatible with other linux tools and caused problems with other FAT implementations (mostly in embedded). See for more details into fatlabel manpage into COMPATIBILITY and BUGS section and also October 2017 tests https://www.spinics.net/lists/kernel/msg2640891.html. FAT label is stored in directory entry and also linux kernel disallow you to create a file or directory with `:` in name. Lowercase letters is one allowed exception as they are allowed also by other FAT implementations (e.g. Linux kernel). Now both blkid and fatlabel are aligned to be compatible with MS-DOS and Windows NT implementations, so finally it should not happen that one tool/system see totally different FAT label as another tool/system. But if you find any other issue, please let us know.

**Comment by patatetom** [comment]
thank you for these precisions.
I was just using the `:` character in my label because it could not be used from Windows (which theoretically prevented a Windows administrator/user from using this same label).
I'm going to look for another solution, but I really would have preferred that `mkfs.fat` remains capable of that, even if it means adding an `-f` switch to force/bypass the big warning.
regards.

**Comment by pali** [comment]
I'm not sure if it is a good idea to allow creating filesystem which violates specification and laos other imlementations have problem to access/modify it. Primary use of FAT these days is a compatibility and interopability with other systems. So I'm not a big fan of using or creating _linux specific_ extensions to FAT and claiming that such fs is still FAT.

Anyway, I know what Microsoft itself in their fastfat.sys implementation violates their own Microsoft FAT specification, so for compatibility with Windows we need to implement FAT in a way like it is in fastfat.sys. So if you find a way how to instruct Windows via their fastfat.sys implementation to put `:` (or any other character) into label and describe steps, I could try to implement it. But in 2017 I have done a big investigation on this topic and I doubt that this is possible. Note that nowadays Microsoft released fastfat.sys source code under MS-PL license which allows any redistribution or modifications, so it is friendly to research.

**Comment by patatetom** [comment]
thanks.
