### ISSUE TITLE
Does mkfs.fat send the TRIM command to SSDs?

### ISSUE THREAD

**Issue by mb720** [dosfstools/dosfstools#163]
When formatting an SSD with `mkfs.fat`, does it send the [TRIM command](https://en.wikipedia.org/wiki/TRIM_(SSD_command)) to the SSD, signalling that the data region can be garbage-collected?

**Comment by pali** [comment]
No, `mkfs.fat` does not issue `BLKDISCARD` ioctl during formatting.

But if you want to discard/trim data on your SSD prior formatting it to FAT, you can call de-facto standard `blkdiscard` command from util-linux project to do it.
