### ISSUE TITLE
The FAT_NO_83NAME flag conflicts with encryption metadata

### ISSUE THREAD

**Issue by msuhanov** [dosfstools/dosfstools#170]
Hello.

Modern versions of Microsoft Windows allow users to encrypt files stored on FAT volumes [1]. The encryption is done at the file system level. The plaintext data is padded (its size must be aligned to 16 bytes), the encrypted data is written to file clusters after the EFS file header [2].

Currently, the NTByte field in the FAT directory entry (its offset is 12 bytes and its length is 1 byte, the field is called _lcase_ in this project) is used to:
* mark the "short" base name as lowercase,
* mark the "short" extension as lowercase,
* mark file data as encrypted,
* mark the file as having a non-standard (large) EFS file header,
* store the padding size (as 4 bits according to the bit mask 0xE4; since the padding can't be larger than 15 bytes, it fits 4 bits).

Microsoft Windows is using the stored padding size to calculate the decrypted file size when listing a directory.

Currently, all bits of the NTByte field are used.

The FAT_NO_83NAME flag is defined here:
https://github.com/dosfstools/dosfstools/blob/5fe59602a937e5ce5f4890fd2e4a27ae50e2b082/src/fsck.fat.h#L198

And then it's used in multiple places (only those potentially leading to problems are listed):
https://github.com/dosfstools/dosfstools/blob/ac4aa79cc264771e5c7e0cd8abea162ed3549042/src/check.c#L163
https://github.com/dosfstools/dosfstools/blob/ac4aa79cc264771e5c7e0cd8abea162ed3549042/src/check.c#L277
https://github.com/dosfstools/dosfstools/blob/ac4aa79cc264771e5c7e0cd8abea162ed3549042/src/check.c#L319

This flag conflicts with the padding size of 2 bytes, because it results in the 0x20 bit being set (i.e., when the padding size of an encrypted file is 2 bytes, the file will be treated as having the FAT_NO_83NAME flag set).

This leads to unwanted behavior, for example:
```
$ /sbin/fsck.fat -v -n -l fat_encrypted_with_bad_sfn.raw
fsck.fat 4.1 (2017-01-24)
Checking we can access the last sector of the filesystem
Boot sector contents:
System ID "MSDOS5.0"
Media byte 0xf8 (hard disk)
       512 bytes per logical sector
      4096 bytes per cluster
      6170 reserved sectors
First FAT starts at byte 3159040 (sector 6170)
         2 FATs, 32 bit entries
    517632 bytes per FAT (= 1011 sectors)
Root directory start at cluster 2 (arbitrary size)
Data area starts at byte 4194304 (sector 8192)
    129280 data clusters (529530880 bytes)
63 sectors/track, 255 heads
       128 hidden sectors
   1042432 sectors total
Checking file /
Checking file /ENCRYPTI.ON
Checking file /System Volume Information (SYSTEM~1)
Checking file /T:ST1.TXT
Checking file /$RECYCLE.BIN
Checking file /test2.txt.PFILE (T:ST2T~1.PFI)
/T:ST1.TXT
  Bad short file name (T:ST1.TXT).
  Auto-renaming it.
  Renamed to FSCK0000.000
Checking file /System Volume Information/.
Checking file /System Volume Information/..
Checking file /System Volume Information/WPSettings.dat (WPSETT~1.DAT)
Checking file /System Volume Information/EDP
Checking file /System Volume Information/EDP/.
Checking file /System Volume Information/EDP/..
Checking file /System Volume Information/EDP/Recovery (RECOVERY)
Checking file /System Volume Information/EDP/Recovery/.
Checking file /System Volume Information/EDP/Recovery/..
Checking file /$RECYCLE.BIN/.
Checking file /$RECYCLE.BIN/..
Checking file /$RECYCLE.BIN/DESKTOP.INI
Checking for unused clusters.
Checking free cluster summary.
Leaving filesystem unchanged.
fat_encrypted_with_bad_sfn.raw: 9 files, 10/129280 clusters
```
Here, two files have invalid short file names (containing the ":" character). The "T:ST1.TXT" file is unencrypted, the "T:ST2T~1.PFI" file is encrypted.

The tool ignored the corruption for the encrypted file. A sample file system image is attached: [fat_encrypted_with_bad_sfn.raw.gz](https://github.com/dosfstools/dosfstools/files/7533608/fat_encrypted_with_bad_sfn.raw.gz) (note that the corruption was made using a HEX editor, this is a simulated image, anything else, including encryption metadata, has been natively created using Microsoft Windows 11).

Please, consider removing the support for the FAT_NO_83NAME flag, it's not implemented in modern operating systems (or make this support optional, triggered by a command-line argument).

**Links**
1. https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/d4bc551b-7aaf-4b4f-ba0e-3a75e7c528f0#Appendix_A_140
2. https://patents.google.com/patent/US10726147B2/en (note that the Windows implementation doesn't use the trailing directory entry approach)

**Comment by pali** [comment]
Interesting... I did not know that FAT supports encryption and there are existing implementations. And also I did not know that dosfstools uses other bits from NTbyte field than for lower/upper case.

For FAT_NO_83NAME support I found following kernel patch https://lore.kernel.org/linux-fsdevel/19045.11460.815706.98797@samba.org/ which seems never entered into mainline kernel and I have never heard about it.

I found that open source version of Microsoft fastfat.sys driver has documented EFS encryption bits, but only 4 bits of total 8 NT bits are there:
https://github.com/microsoft/Windows-driver-samples/blob/d3ec258921cfcef7b053b5a2c866330d43dd3f03/filesys/fastfat/fat.h#L339-L362

Is there any better documentation for those NT bits? Because I do not see padding header size mentioned in that patent.

Anyway, I do not see any other tool which use FAT_NO_83NAME, so it should be really removed from dosfstools and let dosfstools to not check for 8.3 names when encryption bit is set.

**Comment by msuhanov** [comment]
> I found that open source version of Microsoft fastfat.sys driver has documented EFS encryption bits, but only 4 bits of total 8 NT bits are there

It seems that Microsoft removed the EFS code from the open source driver, but left some declarations intact.

> Because I do not see padding header size mentioned in that patent.

The patent states:
_In an embodiment in which the method of FIG. 3 is integrated into the FAT32 file system and AES-CBC encryption is employed, **the four (4) remaining reserved (i.e., undefined) bits of the NtByte field of the FAT short directory entry may be used to store the number of padding bytes of the last 16-byte block of the file (that is, N=4)**. In order for the up-level file system to present the file to the user, the true size of the file may be computed by taking the file size of the entire file, subtracting the size of the header, and then subtracting the number of padding bytes._

> Is there any better documentation for those NT bits?

I did some reverse engineering. I'm not aware of other sources documenting how exactly these 4 bits are stored in the NTByte field.

> let dosfstools to not check for 8.3 names when encryption bit is set

I think these name should be checked. Any reason not to validate them?

**Comment by pali** [comment]
> I think these name should be checked. Any reason not to validate them?

And do we know how to validate these names? If we do not have documentation which describes valid bytes which can appear in encrypted file name then I really do know how to validate them.

**Comment by msuhanov** [comment]
It's the same name as usual (the file names aren't encrypted, only the file data is).

**Comment by pali** [comment]
Ok, in this case, check could be same.

**Comment by msuhanov** [comment]
Just to document possible issues.

* The _bad_name_ function returns success, the actual name checks are skipped (this was demonstrated in the first message here). This affects encrypted files with invalid short file names and with the padding size of 2 bytes (or any other padding size meeting the following condition: _padding_size & 2 > 0_).
* The _auto_rename_ and _rename_file_ functions change the "real" (decrypted) size of the encrypted file. This affects encrypted files with the padding size of 2 bytes (or any other padding size meeting the following condition: _padding_size & 2 > 0_) when there is a duplicate file name within the parent directory index (and a user decides to rename the encrypted file).

The modified "real" (decrypted) size is shown below (_fat_encrypted_duplicate_dirent.raw.orig_ is the file system image with a duplicate file name entry, _fat_encrypted_duplicate_dirent.raw_ is the same image after _fsck.fat_):

![binary diff](https://user-images.githubusercontent.com/7497142/141697041-5cdf3867-f4d5-4d13-8d1c-953b503e1338.png)

The "real" (decrypted) size, as reported by Microsoft Windows 11 for the _fat_encrypted_duplicate_dirent.raw_ image, is 16 bytes (should be 14 bytes).

**Comment by pali** [comment]
Are you going to prepare pull request with fixes?

**Comment by msuhanov** [comment]
Yes, in a few days.
