### ISSUE TITLE
Please clarify licensing of the dummy boot sector

### ISSUE THREAD

**Issue by patrakov** [dosfstools/dosfstools#18]
The src/mkfs.fat.c file is currently licensed as GPLv3 or later. So, this also applies to the dummy boot code contained there. Thus, everyone who did the steps below is, technically, guilty of GPLv3 violation. It's likely that it's not what you want. If that's the case, please relicense the dummy boot code more permissively.

The steps are:
1. Take a USB flash drive.
2. Format it using mkfs.fat.
3. Give the flash drive to someone else, without also giving dosfstools source.

**Comment by andreasbombe** [comment]
I will try, but I have to research who actually wrote that part. That was long before I took over, even before git history started with version 2.11.

To be honest, I don't see it as much of a problem. All that the dummy boot code does is write a string and then wait for a key press. Basically, it's a Hello World program that instead prints a different message. Given its triviality and the fact that a web search for "BIOS hello world" brings up a bunch of tutorials that end up with almost exactly the same code, I'd say that little block of code is probably not even copyrightable.

**Comment by jristz** [comment]
Why not just redone it yourself and pretify it a little, then ypu will not need to search the person that do it and is now your code.

**Comment by pali** [comment]
mkdosfs 0.3 - 28th January 1995		H. Peter Anvin (hpa@yggdrasil.com)
https://github.com/dosfstools/dosfstools/blob/master/doc/ChangeLog.mkdosfs
> Added bogus boot sector code that on attempts to boot prints a message (which can be chosen at mkdosfs time) and lets the user press any key and try again.

Seems to be GPLv2+.

**Comment by jristz** [comment]
it can be GPL2 or GPL2+ depending on the licence used during that time, additionally as the message say is "bogus" so it not a fix but a workaround and "chosen at mkdosfs time" I never see an example or use of it neither in manpages or in other places.

I should preffer a better implementation and properly document it with examples this time.
but the main issue look nearly solved.

**Comment by pali** [comment]
At that time it was GPLv2+.

**Comment by jristz** [comment]
then in that case the only thing should be either add a licence field to the files generating this sector and/or make the dumy now print info about dosfstools maybe

**Comment by andreasbombe** [comment]
I will reiterate that I don't see the included boot sector code as being of sufficient originality so as to be copyrightable. "Hello world" type programs generally aren't really, and that's basically what it is (and what you'll find almost identically when you search for a BIOS boot sector hello world program), except with a different text than "hello world".

I might try asking hpa for an explicit license statement again, just to put this to rest.

**Comment by pali** [comment]
@andreasbombe Something like public domain code?

**Comment by pali** [comment]
> mkdosfs 0.3 - 28th January 1995	 H. Peter Anvin (hpa@yggdrasil.com)
> https://github.com/dosfstools/dosfstools/blob/master/doc/ChangeLog.mkdosfs
> > Added bogus boot sector code that on attempts to boot prints a message (which can be chosen at mkdosfs time) and lets the user press any key and try again.
> 
> Seems to be GPLv2+.

I contacted H. Peter Anvin and he allowed to put that boot secotor code into public domain.

So I guess this problem is solved now.
