### ISSUE TITLE
When going from windows to a hibernated Linux , my files were lost from USB stick

### ISSUE THREAD

**Issue by threader** [dosfstools/dosfstools#199]
I can try to reproduce the issue but from multiple minor changes it was gone when mounting the drive again in Linux, even though I'd saved and tested from PowerShell ISE..... I've got no clear answer but the file allocation table is cached, but why my perfectly working script is gone I do not know.... The fs was NTFS , i was only supposed to commit from git in Linux , i tried to write what I remembered, but I've if or not self poisoned due to some alcohol, If anyone can tell me how it can take 4 days and still be dizzy, and fall down the first day after 17 hours drooling in bed, please tell me

**Comment by pali** [comment]
I do not see how is this issue related to the dosfstools project and mkfs.fat which purpose is to erase data on device.

**Comment by pali** [comment]
Marking as a spam.
