### ISSUE TITLE
A question about "lfn_fix_checksum"

### ISSUE THREAD

**Issue by xianbeii** [dosfstools/dosfstools#205]
Resently I fould that there are not one references of "lfn_fix_checksum" in all files. I know that this functions was referenced in "rename_file" and "auto_rename". May I ask Why this function is preserved but is not referenced anywhere?

**Comment by pali** [comment]
I'm not sure. Its usage was removed in commit 4f953bb5d74e0eeda6cbee1e4871513edc7b912b and if you look at commit message, it seems that this situation can be improved and then lfn_fix_checksum() function can be usefull.

**Comment by xianbeii** [comment]
Oh, i got it. Thx a lot for your reply! have a good day!
