### ISSUE TITLE
fsck.fat does not complain when "." and ".." are not the very first non-root directory table entries

### ISSUE THREAD

**Issue by fstirlitz** [dosfstools/dosfstools#32]
`fsck.fat` does not detect it as an error when dot and dot-dot entries are not the very first two entries in a non-root directory table; it will only complain when these entries are missing altogether. Microsoft's ScanDisk considers either condition to be an error. Additionally, even when it is detected, `fsck.fat` cannot fix the problem.

Issue found while investigating [QEMU bug #1599539](https://bugs.launchpad.net/qemu/+bug/1599539).

**Comment by pali** [comment]
In pull request https://github.com/dosfstools/dosfstools/pull/79 is a detection of those problems.
