### ISSUE TITLE
Error when Compiling configure.ac with autoconf

### ISSUE THREAD

**Issue by The-Loud** [dosfstools/dosfstools#37]
autoconf
Gives me an m4_allocate_allow warning but builds the configure script.

root:/sources/dosfstools# ./configure --prefix=/usr
./configure: line 2090: syntax error near unexpected token `1.11'

./configure: line 2090: `AM_INIT_AUTOMAKE(1.11 foreign subdir-objects parallel-tests)'

This is on a partially built LFS system, however I also tried it on the ubuntu host and received the same configure.ac warnings and configure error.

**Comment by andreasbombe** [comment]
I have never seen that warning. The fact that the macro invocation ends up unmodified in `configure` points to missing automake. Do you have it installed (minimum version 1.11) and did you run `automake`?

In the README I recommend `autoreconf -i` to automatically do everything needed including automake and autoconf.

**Comment by The-Loud** [comment]
Apologies, I missed that last line. I ran autoconf -i and it compiled successfully and installed properly.

Many thanks.
