### ISSUE TITLE
Usage of "Dirty Bit" does not meet FAT specification

### ISSUE THREAD

**Issue by smklein** [dosfstools/dosfstools#38]
It seems that fsck is using byte "0x41" (FAT32) or "0x25" (FAT16) as as the containing byte of this bit.

However, the FAT specification indicates that the first two clusters of a FAT are reserved for information which includes this dirty bit (notably, not within the boot sector). It also mentions that byte 0x41/0x25 is "BS_Reserved1", which "is "Reserved (used by Windows NT). Code that formats FAT volumes should always set this byte to 0."

Apparently, fsck's behavior isn't wrong -- there are other (informal) third party sources that confirm the usage of byte 0x41 / 0x25 as dirty bits. However, I can't find any formal documentation for this "out of spec" dirty bit -- or any reasoning why the documented dirty bit is going unused.

Additionally, there doesn't seem to be any attempt by fsck to set the formally specified "ClnShutBitMask" to "clean" after a verification pass.

**Comment by jristz** [comment]
Do you can link the specification document to give a check?

I think maybe as you say 0x41/0x25 is "BS_Reserved1", which is "Reserved (used by Windows NT)" maybe Windows NT add they dirty bit too aditionally to the one in the specification, so they are documenting FAT dirty bit but not NT doings.

**Comment by smklein** [comment]
https://staff.washington.edu/dittrich/misc/fatgen103.pdf

Page 18:

**What are the two reserved clusters at the start of the FAT for? The first reserved cluster, FAT[0],
contains the BPB_Media byte value in its low 8 bits, and all other bits are set to 1. For example, if the
BPB_Media value is 0xF8, for FAT12 FAT[0] = 0x0FF8, for FAT16 FAT[0] = 0xFFF8, and for
FAT32 FAT[0] = 0x0FFFFFF8. The second reserved cluster, FAT[1], is set by FORMAT to the EOC
mark. On FAT12 volumes, it is not used and is simply always contains an EOC mark. For FAT16 and
FAT32, the file system driver may use the high two bits of the FAT[1] entry for dirty volume flags (all
other bits, are always left set to 1). Note that the bit location is different for FAT16 and FAT32,
because they are the high 2 bits of the entry.**

**Comment by pali** [comment]
> I can't find any formal documentation for this "out of spec" dirty bit ...

Authoritative information could be Microsoft Windows FAT driver implementation (fastfat.sys). Sources of fastfat.sys are available now on github: https://github.com/Microsoft/Windows-driver-samples/tree/master/filesys/fastfat

https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/fat.h#L209
> We use the CurrentHead field for our dirty partition info.
> 
> #define FAT_BOOT_SECTOR_DIRTY            0x01
> #define FAT_BOOT_SECTOR_TEST_SURFACE     0x02

https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/verfysup.c#L729
> For compatibility with Win9x, we manipulate both the historical DOS (on==clean in index 1 of the FAT) and NT (on==dirty in the CurrentHead field of the BPB) dirty bits.

**Comment by pali** [comment]
Checking and setting DOS Clean Shutdown bit by fsck.fat is implemented in this pull request: https://github.com/dosfstools/dosfstools/pull/100
