### ISSUE TITLE
fsck.fat complains about spaces in file names

### ISSUE THREAD

**Issue by fstirlitz** [dosfstools/dosfstools#39]
`fsck.fat` complains about short file names with spaces in the middle (with the exception of `EA DATA. SF` and `WP ROOT. SF`), even though they are actually sort-of permitted under DOS; the syscall interface (INT 21h) allows using them, and Microsoft tools don't complain about them. The COMMAND.COM from Windows 9x even allows you to do this (outside a Windows session, of course):
```
C:\TEST>mkdir "1 2 3"

C:\TEST>echo foo > "7 8 9"

C:\TEST>type "7 8 9"
foo

C:\TEST>dir /b
1 2 3
7 8 9

```

Given that files with such names may be hard to access in DOS programs (which are the main users of short file names), `fsck.fat` should probably keep an option to treat them as invalid.

**Comment by andreasbombe** [comment]
You're right, I don't see anything in the spec specifically forbidding spaces except at the beginning of the name. I will look into it.
