### ISSUE TITLE
mkfs.fat: automatic FAT32 selection

### ISSUE THREAD

**Issue by japm48** [dosfstools/dosfstools#42]
Currently there is a comment in `mkfs.fat.c` stating: `FAT32 is (not yet) choosen automatically`.

From https://msdn.microsoft.com/en-us/windows/hardware/gg463080.aspx : 
> FAT type—one of FAT12, FAT16, or FAT32—is determined by the count of clusters on the volume and nothing else.

And:
> This is the one and only way that FAT type is determined. There is no such thing as a FAT12 volume that has more than 4084 clusters. There is no such thing as a FAT16 volume that has less than 4085 clusters or more than 65,524 clusters. There is no such thing as a FAT32 volume that has less than 65,525 clusters. If you try to make a FAT volume that violates this rule, Microsoft operating systems will not handle them correctly because they will think the volume has a different type of FAT than what you think it does.

Pretentious general tone of the text apart (e.g. `the world is full of FAT code that is wrong`), I believe mkfs.fat has a dangerous default, as the user must manually calculate whether `-F 32` is required.
So, this is a request to automatically select FAT32 when `size_fat_by_user==0` and the partition has the minimum size required.

In case this isn't reasonable because it breaks backwards compatibility, I suggest as an alternative creating something like `--auto-size` to calculate the size according to the spec. OTOH this would complicate the code...

**Comment by andreasbombe** [comment]
Do you have a specific example of the happening in the real world?

If no FAT size is specified and the target is 512 MiB or larger in size, FAT32 is automatically selected in `establish_params()`. The comment should therefore probably deleted.

**Comment by japm48** [comment]
Ah, OK then.
I was reading that to implement some basic filesystem detection.
Anyways, the check is in the total size, not the number of sectors, but with a default of 512 bytes per sector, I guess it's correct in the default case.
Another comment says `This only works correctly for 512 byte sectors!`, probably hints that some OSs could misdetect the fs type. I'll to do some calculations to see if a *non-conforming* partition can be generated with the defaults.

So, I'd better investigate what Windows `format` is doing. Maybe they don't even respect their own rules.

Sorry for the noise, and please remove the misleading comment.
Feel free to close this, I'll reopen if I come up with a better implementation idea.

**Comment by andreasbombe** [comment]
The code base is really quite old and not all that easy to follow the way it has grown back then. This particular selection being split over two function is really not so great. At least there's already checks whether the cluster count matches the requested FAT size, so if there was a mistake, it would be reported.

For now, I've just changed the comment.
