### ISSUE TITLE
can't find a header file fatal error

### ISSUE THREAD

**Issue by lalith12** [dosfstools/dosfstools#49]
fatal error: iconv.h: No such file or directory

i looked into it but no file is present names iconv.h

**Comment by xftroxgpx** [comment]
for me, on ArchLinux, 
```
$ pacman -Qo /usr/include/iconv.h
/usr/include/iconv.h is owned by glibc 2.25-2

```

**Comment by lalith12** [comment]
its fixed but i am getting a other one undefined reference to lidiconv
