### ISSUE TITLE
libiconv_open unreferenced make error

### ISSUE THREAD

**Issue by lalith12** [dosfstools/dosfstools#50]
the error after intalling libiconv-1.5 while:

charconv.o: In function `iconv_init_codepage':
/cygdrive/c/Users/x/Documents/mygame/magh4862/dosfstools-4.1/src/charcon                                 v.c:12: undefined reference to `libiconv_open'
/cygdrive/c/Users/x/Documents/mygame/magh4862/dosfstools-4.1/src/charcon                                 v.c:12:(.text+0x2f): relocation truncated to fit: R_X86_64_PC32 against undefine                                 d symbol `libiconv_open'
charconv.o: In function `dos_char_to_printable':
/cygdrive/c/Users/x/Documents/mygame/magh4862/dosfstools-4.1/src/charcon                                 v.c:58: undefined reference to `libiconv'
/cygdrive/c/Users/x/Documents/mygame/magh4862/dosfstools-4.1/src/charcon                                 v.c:58:(.text+0x195): relocation truncated to fit: R_X86_64_PC32 against undefin                                 ed symbol `libiconv'

**Comment by andreasbombe** [comment]
So I'm guessing this is Cygnus on Windows. Since this is after the other issue you reported, have you restarted `./configure` before compiling? If so, can you provide the log of the compilation?

There might be something missing from the autoconf configuration, I'll have to check.

**Comment by lalith12** [comment]
dude i got it figured but the only bin files i get is this three 
1.fatlabel
2.mkfs.fat
3.fsck.fat
and i need mkfs.msdos which is not present

**Comment by andreasbombe** [comment]
`mkfs.msdos` is just an alternative name for `mkfs.fat` (like `mkfs.vfat` and `mkdosfs`).

Can you say how you fixed it? There might still be some problem with autoconf if it doesn't happen automatically.

**Comment by lalith12** [comment]
i passed the libiconv.a externally when configuring and after the errors are gone .
and whare can i get libudev for mkfs.fat

**Comment by andreasbombe** [comment]
You can't, not on Cygwin. It's used on Linux but is not required.

**Comment by lalith12** [comment]
and about the log file you asked me is it after executing make
