### ISSUE TITLE
View/Change volume-id

### ISSUE THREAD

**Issue by pali** [dosfstools/dosfstools#52]
Currently it is possible to specify volume-id (UUID) when formatting via `-i` mkdosfs option. But it is not possible to view volume-id of some existing file system and also it is not possible to change it.

Please provide some tool for view and change volume-id.

**Comment by pali** [comment]
Currently the only tool which can change FAT volume-id is mlabel from mtools package. Its usage is a quite complicated as mtools normally operates on drive A: which is configured via /etc/mtools.conf (by default to /dev/fd0, floppy disk) and uses C-H-S geometry of hard disks...

Here is example how to set volume-id `0BCE06B2` to FAT device /dev/sda1:
```
$ MTOOLS_SKIP_CHECK=1 mlabel -N 0BCE06B2 :: -i /dev/sda1
```

**Comment by wdlkmpx** [comment]
Yeah mtools is designed to give you headaches. Both projects are GPLv3.. so if something is missing in dosfstools.. it might be a good idea to port stuff from mtools..

**Comment by andreasbombe** [comment]
Don't worry, I will get around to it. It really shouldn't be hard to do this, so I doubt I'll need to port anything from mtools. In fact, most of the work will probably be the extra option parsing in fatlabel, where I intend to put this.

**Comment by pali** [comment]
GUI partitions programs needs this functionality:
* read current volume-id
* set volume-id to supplied one
* set volume-id to random one

So it would be great to see new tool (or extending some existing) to support these actions.

**Comment by pali** [comment]
@andreasbombe do you have any plans for such tool?
