### ISSUE TITLE
FAT32 FS Information Sector overwrote by boot sector backup

### ISSUE THREAD

**Issue by zhangyoufu** [dosfstools/dosfstools#74]
`mkfs.fat` arguments: `-F 32 -R 2`

the content of sector 0 and 1 are same while the EBPB still points FS Information Sector at sector 1

```
	    backup_boot = (reserved_sectors >= 7) ? 6 :
		(reserved_sectors >= 2) ? reserved_sectors - 1 : 0;
```

**Comment by pali** [comment]
Same problem as desribed in https://github.com/dosfstools/dosfstools/issues/110

FSINFO sector is mandatory for FAT32, but backup boot sector is optional. Therefore when there are only two sectors in reserved FAT area, first must be boot sector and second must be FSINFO sector. And there is not backup boot sector.

So above code is wrong.
