### ISSUE TITLE
minimum number of clusters for FAT32

### ISSUE THREAD

**Issue by zhangyoufu** [dosfstools/dosfstools#75]
mkfs.fat.c:
```
#define MIN_CLUST_32    65529
```

according to Microsoft Extensible Firmware Initiative FAT32 File System Specification
```
If(CountofClusters < 4085) {
   /* Volume is FAT12 */
} else if(CountofClusters < 65525) {
   /* Volume is FAT16 */
} else {
   /* Volume is FAT32 */
}
```

maybe we should change `MIN_CLUST_32` to 65525 ?

**Comment by pali** [comment]
Beware that there are logical errors in Microsoft FAT32 specifications, specially in clusters formulas. Project mtools documented some of those errors. So before change I would suggest to check if this calculated number in Microsoft documentation is correct or not.

**Comment by zhangyoufu** [comment]
comment for calc_fat_bits2 in mformat.c
```
/*
 * According to Microsoft "Hardware White Paper", "Microsoft
 * Extensible Formware Initiative", "FAT32 File System Specification",
 * Version 1.03, December 6, 2000:
 * If (CountofClusters < 4085) {
 *  // Volume is FAT12
 * } else if (CountofClusters < 65525) {
 *  // Volume is FAT16
 * } else {
 *  //Volume is FAT32
 * }
 *
 * This document can be found at the following URL
 * http://www.microsoft.com/hwdev/download/hardware/fatgen103.pdf
 * The relevant passus is on page 15.
 *
 * Actually, experimentations with Windows NT 4 show that the
 * cutoff is 4087 rather than 4085... This is Microsoft after all.
 * Not sure what the other Microsoft OS'es do though...
 */
```

According to [fastfat.sys](https://github.com/Microsoft/Windows-driver-samples/blob/5d61a4a79a1e96dc5d9af1e5e712c84507307544/filesys/fastfat/fat.h#L506), as long as SectorsPerFat equals 0, the partition will be treated as FAT32.

**Comment by andreasbombe** [comment]
`MIN_CLUST_32` was introduced in 2.11, which is unfortunately before the git repo was started. This is what CHANGES has to say:

    mkdosfs: raised FAT12_THRESHOLD from 4078 to 4085, introduced MIN_CLUST_32

Also note that `MAX_CLUST_16` and `MIN_CLUST_32` are a bunch of clusters apart, so this appears to create a safety buffer between FAT16 and FAT32. Quite likely in response to one fragile implementation or other.

Lowering that value by a few clusters will gain us nothing (except FAT32 filesystems with 65525-65528 clusters) while decreasing the safety buffer.
