### ISSUE TITLE
dosfstools 4.1 compilation failed with glibc 2.27 version.

### ISSUE THREAD

**Issue by RajeshDasari** [dosfstools/dosfstools#85]
Hi ,

I am compiling the dosfstools 4.1 version with gcc 4.9.4 and glibc 2.27 and i am getting the below error.

x86_64-linux-gnu-gcc  --sysroot=/home/work/x86_64/rootfs/x86_64-linux-gnu -Wall -Wextra -Wno-sign-compare -Wno-missing-field-initializers -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings  -g -O2 -L/usr/lib64 -ludev  -o testdevinfo testdevinfo-testdevinfo.o testdevinfo-device_info.o blkdev/testdevinfo-blkdev.o blkdev/testdevinfo-linux_version.o  
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libm.so.6: undefined reference to `__strtof128_nan@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libpthread.so.0: undefined reference to `_IO_enable_locks@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libpthread.so.0: undefined reference to `__mmap@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libpthread.so.0: undefined reference to `__munmap@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libresolv.so.2: undefined reference to `__resolv_context_get@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libresolv.so.2: undefined reference to `__resolv_context_get_override@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libpthread.so.0: undefined reference to `__mprotect@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libpthread.so.0: undefined reference to `__tunable_get_val@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libresolv.so.2: undefined reference to `__resolv_context_get_preinit@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/librt.so.1: undefined reference to `__close_nocancel@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libpthread.so.0: undefined reference to `__sigtimedwait@GLIBC_PRIVATE'
/home/work/x86_64/rootfs/x86_64-linux-gnu/lib64/libresolv.so.2: undefined reference to `__resolv_context_put@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:435: testdevinfo] Error 1
make[4]: *** Waiting for unfinished jobs....
mv -f .deps/mkfs_fat-mkfs.fat.Tpo .deps/mkfs_fat-mkfs.fat.Po
make[3]: *** [Makefile:400: all-recursive] Error 1

The same dosfstools version compilation was successful with the gcc 4.94 and glibc 2.24. Is this any know issue, Please provide your inputs.

Regards,
Rajesh.

**Comment by andreasbombe** [comment]
All the errors appear to be shared libraries not finding glibc symbols. As such it doesn't appear to have anything in particular to do with dosfstools. It looks like your shared libraries are compiled for a newer version of glibc and are not finding expected symbols in the version that is there.

Does your compilation environment successfully compile (or even run) any other programs?

**Comment by RajeshDasari** [comment]
Hi ,

all the other programmes other than dosfstools was successful.
I am doing a cross compilation with the new sysroot which has glibc 2.27 libraries.
where as host has gibc 2.24 libraries.

I see that UDEV_LIBS is set to "-L/usr/lib64 -ludev" and this is trying to link the libraries from the host machine.

For now i have passed UDEV_LIBS to configure to fix this issue, like below.
/configure UDEV_LIBS="-ludev"

is there any other way to fix this issue.

**Comment by andreasbombe** [comment]
The flags come from the pkg-config configuration of libudev. If they break your compilation you would have to look your libudev installation to figure out why it hands out flags that are unsuitable for you.

An alternative is to build without udev by running `./configure --without-udev`.

**Comment by andreasbombe** [comment]
Closing as this seems to be an issue with the user's build system rather than dosfstools..
