### ISSUE TITLE
fsck.fat doesn't report error on shrunk device unless run with '-t' option

### ISSUE THREAD

**Issue by ashegoulding** [dosfstools/dosfstools#99]
I was curious as to what happens if you accidentally shrink file systems. So far, I've found that the developers of btrfs, exfat, and vfat didn't think this through.

```
truncate -s 1G a
mkfs.vfat a
fsck.vfat a

truncate -s 1073733632 a
# no error
fsck.vfat a
# error
fsck.vfat -t a
```

**output**
```
fsck.fat 4.1 (2017-01-24)
Cluster 261628 is unreadable.
Cluster 261629 is unreadable.
Free cluster summary wrong (261627 vs. really 261625)
1) Correct
2) Don't correct
? 
```

This case is actually an error on extN, xfs, and cramfs. I think that, for the sake of consistency, fsck.fat should report it as error, too.

**Comment by pali** [comment]
Yea, fsck.fat should check that last cluster in FAT table is not behind end of disk as a first step.

But even this problem could be fixed/repaired. If you (accidentally) shrinked disk partition and on freed place has not contained any referenced data then you have not lost anything. Just FAT tables needs to be updated/fixed. And this could be implemented in fsck.fat.

On the other hand if you shrinked disk partition in such way that "removed" data, then fsck.fat needs to traverse whole FAT table and detect what was removed and properly clean this dirty state (remove non-existent files and directories, etc...). This could make damaged FAT partition partially recoverable.

Anyway, tool for resizing FAT filesystems is missing, see: https://github.com/dosfstools/dosfstools/issues/91

**Comment by pali** [comment]
Pull request https://github.com/dosfstools/dosfstools/pull/114 addressed this issue and after merging it fsck.fat in above example fails with error:

    Checking we can access the last sector of the filesystem
    Failed to read sector 2097151.
